apiVersion: v2
name: gatekeeper
description: Zero-trust reverse proxy gateway — Helm chart
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - zero-trust
  - reverse-proxy
  - gateway
  - authentication
  - rbac
  - opa
home: https://github.com/noob-master-cell/Gatekeeper
sources:
  - https://github.com/noob-master-cell/Gatekeeper
maintainers:
  - name: Gatekeeper
